"use client"

import { Providers } from "./providers";
import { Amplify } from 'aws-amplify';
import config from '@/amplifyconfiguration.json';
import '@aws-amplify/ui-react/styles.css';
import '../styles/styles.css';
import {NextUIProvider} from "@nextui-org/react";
import type { AppProps } from 'next/app';
import React, { useEffect } from "react";
import { AuthUser, getCurrentUser, signOut } from 'aws-amplify/auth';
import NavBarHeader from '@/components/NavBarHeader';
import { Hub } from "aws-amplify/utils";
import Whatsapp from '@/components/Whatsapp';
import Footer from '@/components/Footer';

// configure the Amplify client library with the configuration generated by `amplify sandbox`
Amplify.configure(config);



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const [user, setUser] = React.useState<AuthUser | null>(null);
  async function getUser() {
    try {
      const { username, userId, signInDetails } = await getCurrentUser();
      setUser({ username, userId, signInDetails });
      console.log(`The username: ${username}`);    
    } catch (err) {
      console.log(err);
      setUser(null);
    }
  }
  useEffect(() => {
    const unsubscribe = Hub.listen("auth", ({ payload }) => {
      switch (payload.event) {
        case 'signedIn':
        case 'signedOut':        
          getUser();
          break;
        
      }
    });
    getUser();
    return () => {
      unsubscribe();
    };
  }, []);
  return (
    <html lang="en">
      <body className="h-full min-h-screen bg-white dark:bg-[#0F172A]">
        <Providers>
        <NextUIProvider className='min-h-screen flex flex-col justify-start'>    
  <NavBarHeader user={user} signOut={signOut} />
  {children}
  <div className="footer fixed bottom-3 right-14">
    <Whatsapp />
  </div>
  <Footer />
  </NextUIProvider>
          
        </Providers>
      </body>
    </html>
  );
}
