"use client"

import { Providers } from "./providers";
import { Amplify } from 'aws-amplify';
import config from '@/amplify_outputs.json';
import '@aws-amplify/ui-react/styles.css';
import '../styles/styles.css';
import {HeroUIProvider} from "@heroui/react";
import React, { useEffect } from "react";

import NavBarHeader from '@/components/NavBarHeader';

import Whatsapp from '@/components/Whatsapp';
import Footer from '@/components/Footer';

import { Authenticator } from '@aws-amplify/ui-react';

// configure the Amplify client library with the configuration generated by `amplify sandbox`
Amplify.configure(config);


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
    <body className=" bg-white dark:bg-[#0F172A] sm:w-full h-full">
    
    <Authenticator.Provider>
      <Providers>
      <HeroUIProvider>    
      <div className="flex flex-col min-h-screen">
<NavBarHeader  />
{children}
<div className="footer fixed bottom-3 right-14">
  <Whatsapp />
</div>
<footer className="mt-auto bg-gray-200  text-center">
<Footer />
      </footer>
      </div>
</HeroUIProvider>
        
      </Providers></Authenticator.Provider>
    </body>
  </html>
  );
}
