import Head from "next/head";
import React, { use, useEffect } from "react";
import ButtonSection from "@/components/ButtonsSection";
import FacebookFeed from "@/components/FacebookFeed";
import Image from "next/legacy/image";
import portada from '../public/portada.png'
import { Divider, Button } from "@heroui/react";
import SocialMediaBar from "@/components/SocialMediaBar";
import YouTubeFeed from "@/components/YoutubeFeed";
import SocialMediaHorizontal from "@/components/SocialMediaHorizontal";

export default function Home() {

  return (
    <>
      <Head>
        <title>Capacitaciones casa del menor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="w-full h-full bg-white">
          <div className="w-full">
            <Image src={portada} alt="En construccion" layout="responsive" />
          </div>
          <div className="w-full">
            <ButtonSection />
            <Divider className="my-4" />
            <div className="flex items-center justify-center pb-8">
              <Button
                className="bg-gradient-to-r from-purple-500 to-indigo-600 text-white shadow-lg text-3xl font-bold py-5" size="lg"
                radius="lg">
                Nuestras publicaciones
              </Button>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 px-40">
              <div className="flex justify-center">
                <FacebookFeed pageUrl="https://www.facebook.com/CasaDelMenorDeBoyaca" />
              </div>
              <div className="flex items-center justify-center">
                <div>
                  <h1 className="text-2xl font-bold">Visita nuestra pagina oficial</h1>
                  <div className="w-screen px-4 sm:px-0 sm:w-auto">
                    <a href="http://www.casadelmenorboyaca.gov.co/" target="_blank">
                      <img src="miniature.png" alt="Casa del menor" />
                    </a>
                  </div>
                </div>
              </div>
            </div>


            <div className="flex items-center justify-center py-8">
              <Button
                className="bg-gradient-to-r from-purple-500 to-indigo-600 text-white shadow-lg text-3xl font-bold py-5" size="lg"
                radius="lg">
                Mirar en Youtube
              </Button>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 px-40">
              <div>
                <YouTubeFeed />
              </div>
              <div className="flex items-center justify-center">
                <div>
                  <h1 className="text-2xl font-bold">Las relaciones interpersonales</h1>
                  <p className="text-justify">Tenemos videos en nuestro canal de youtube, suscribete para recibir notificaciones de nuevos videos</p>
                </div>
              </div>
            </div>

            <div className="flex items-center justify-center py-8">
              <Button
                className="bg-gradient-to-r from-purple-500 to-indigo-600 text-white shadow-lg text-3xl font-bold py-5" size="lg"
                radius="lg">
                Lineas de atencion
              </Button>
            </div>
            <SocialMediaHorizontal />
          </div>

          <SocialMediaBar />
        </div>
      </main>
    </>
  );
}