import Head from "next/head";
import React, { use, useEffect } from "react";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { getCurrentUser } from 'aws-amplify/auth';
import { Link } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });
import Image from 'next/image';
import portada from '../public/portada.png'

export default function Home() {

  return (
    <>
      <Head>
        <title>Capacitaciones casa del menor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="w-full h-full bg-indigo-400">
          <div className="container items-center max-w-6xl px-8 mx-auto xl:px-5">
            <div className="flex flex-wrap items-center sm:-mx-3">
              <div className="w-full  md:px-3">
                <Image src={portada} className="w-screen h-2/3" alt="En construccion" width={800} height={800} />
              </div>

            </div>
          </div>



        </div>

      </main>
    </>
  );
}
