import { Amplify } from 'aws-amplify';
import config from '@/amplifyconfiguration.json';
import '@aws-amplify/ui-react/styles.css';
import '../styles/styles.css';
import {NextUIProvider} from "@nextui-org/react";
import type { AppProps } from 'next/app';



// configure the Amplify client library with the configuration generated by `amplify sandbox`
Amplify.configure(config);

function App({ Component, pageProps }: AppProps) {
  return <NextUIProvider>
    
   
  <Component {...pageProps} />
  </NextUIProvider>;
}

export default App;
