import Head from "next/head";
import React, { use, useEffect } from "react";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { getCurrentUser } from 'aws-amplify/auth';
import {Link} from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });
import Image from 'next/image';

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Capacitaciones casa del menor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
      <section className="px-2 py-32 bg-white md:px-0 tails-selected-element">
  <div className="container items-center max-w-6xl px-8 mx-auto xl:px-5">
    <div className="flex flex-wrap items-center sm:-mx-3">
      <div className="w-full md:w-1/2 md:px-3">
        <div className="w-full pb-6 space-y-6 sm:max-w-md lg:max-w-lg md:space-y-4 lg:space-y-8 xl:space-y-9 sm:pr-5 lg:pr-0 md:pb-0">
        <h1 className="text-4xl font-extrabold tracking-tight text-gray-900 sm:text-5xl md:text-4xl lg:text-5xl xl:text-6xl">
            <span className="block xl:inline">Casa del menor Boyacá</span>
            <span className="block text-indigo-600 xl:inline" data-primary="indigo-600"><br></br>Cuidemos de tu salud mental!</span>
          </h1>
          <p className="mx-auto text-base text-gray-500 sm:max-w-md lg:text-xl md:max-w-3xl">En esta página encontrarás las capacitaciones dadas por los profesionales de la Casa del menor de Boyacá a instituciones públicas. En la parte inferior derecha encontrarás un link a la línea de Whatsapp para resolver dudas o recibir ayuda</p>
          <div className="relative flex flex-col sm:flex-row sm:space-x-4">
            <Link color="foreground" href="/capacitaciones">
            <div className="flex items-center w-full px-6 py-3 mb-3 text-lg text-white bg-indigo-600 rounded-md sm:mb-0 hover:bg-indigo-700 sm:w-auto" data-primary="indigo-600" data-rounded="rounded-md">Mira las presentaciones<svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 ml-1" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="5" y1="12" x2="19" y2="12" className=""></line><polyline points="12 5 19 12 12 19"></polyline></svg>
            </div>
            </Link>
            <a href="#_" className="flex items-center px-6 py-3 text-gray-500 bg-gray-100 rounded-md hover:bg-gray-200 hover:text-gray-600" data-rounded="rounded-md">Otra opción</a>
          </div>
        </div>
      </div>
      <div className="w-full md:w-1/2">
        <div className="w-full h-auto overflow-hidden rounded-md sm:rounded-xl" data-rounded="rounded-xl" data-rounded-max="rounded-full">
          <Image src="/collaboration.svg" className="mr-4" alt="Casa del menor Logo" width={350} height={380}/>
          </div>
      </div>
    </div>
  </div>
</section>
      </main>
    </>
  );
}
